---
- name: Install python-pycurl
  yum: name=python-pycurl state=installed
  become: true

- name: Import jenkins key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no
  become: true

- name: Get jenkins repo for ansible
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Install Java for RedHat
  yum: name=java state=latest
  when: ansible_os_family == "RedHat"
  become: true

- name: Install Jenkins for RedHat
  yum: name=jenkins-1.611 state=latest
  register: jenkins_install
  when: ansible_os_family == "RedHat"
  become: true

- name: Ensure jenkins is running
  service:
    name: jenkins
    state: started
  when: ansible_os_family == "RedHat"
  become: true

- name: Start jenkins on boot
  shell: chkconfig jenkins on
  when: ansible_os_family == "RedHat"
  become: true

- name: Message
  command: echo XXX
#- name: Install plugin
#  jenkins_plugin:
#    name: "build-pipeline-plugin"
#  become: true

#- name: Enable the plugin
#  jenkins_plugin:
#    name: token-macro
#    state: enabled
